spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/liquibaseSupplier;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    liquibase:
        drop-first: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
    api-docs:
        enabled: false
    swagger-ui:
        url: /open-api.yaml
